version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=integrapaydb
    ports:
      - "5432:5432"
    volumes:
      - mydbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    profiles:
      - backend

volumes:
  mydbdata:
