spring.application.name=backend
spring.profiles.active=default
# Use docker-compose service name instead of localhost
spring.datasource.url=jdbc:postgresql://db:5432/integrapaydb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Flyway migrations
spring.flyway.user=user
spring.flyway.password=password
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://db:5432/integrapaydb
