spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/integrapaydb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.user=user
spring.flyway.password=password
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/integrapaydb

jwt.secret=mySecretKey1234567890123456789012345678901234567890
jwt.expiration=86400000

server.servlet.context-path=/api
